// Purpose: Request DTO for customer creation and updates
// File: customer-service/src/main/java/com/nextgenloan/customer/dto/CustomerRequestDto.java
// Dependencies: Jakarta Validation, Lombok

package com.nextgenloan.customer.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Customer Request DTO
 *
 * WHY: This DTO is used for INCOMING requests (POST and PUT).
 * It defines what clients CAN send to the API.
 *
 * SECURITY: Notice that clients cannot set certain fields:
 * - id (auto-generated by the database)
 * - status (set by the service, not the client)
 * - created_at, updated_at (set by the service)
 * - version (set by the service)
 *
 * VALIDATION: We apply validation annotations here.
 * This ensures incoming data is valid BEFORE it reaches
 * the service layer.
 *
 * REAL BANK EXAMPLE: In a banking API, clients can't set
 * their own customer number. The service generates it.
 * This prevents fraud and ensures proper numbering.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CustomerRequestDto {

    // NOTE: customerNumber is NOT required from client
    // The service generates it automatically when registering
    // Only used when provided by admin for updates
    private String customerNumber;

    @NotBlank(message = "First name is required")
    @Size(max = 100, message = "First name must be at most 100 characters")
    private String firstName;

    @NotBlank(message = "Last name is required")
    @Size(max = 100, message = "Last name must be at most 100 characters")
    private String lastName;

    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    @Size(max = 255, message = "Email must be at most 255 characters")
    private String email;

    @Size(max = 20, message = "Phone number must be at most 20 characters")
    private String phoneNumber;

    @NotNull(message = "Date of birth is required")
    private LocalDate dateOfBirth;

    // 
    // EXPLANATION: Why no status field?
    // Clients shouldn't set their own status.
    // The service sets it (e.g., 'PENDING_VERIFICATION' for new customers).
    // In a real bank, status is updated by the service based on
    // verification checks, KYC completion, etc.
    // 

    // 
    // EXPLANATION: Why no audit fields?
    // Clients shouldn't set audit information.
    // The service sets created_by, updated_by based on authenticated user.
    // 
}