// Purpose: JPA entity that maps to the 'customers' table in PostgreSQL
// File: customer-service/src/main/java/com/nextgenloan/customer/entity/Customer.java
// Dependencies: jakarta.persistence, lombok

package com.nextgenloan.customer.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Customer Entity
 *
 * WHY: This class represents the data we store about customers.
 * In a bank, the Customer entity is the source of truth for
 * all customer information. Other services reference customers
 * by their ID or customer number, but they don't own the data.
 *
 * WHAT: Maps to the 'customers' table in PostgreSQL.
 *        Manages customer identity, contact information, and status.
 */
@Entity
@Table(name = "customers")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Customer {

    /**
     * WHY: Primary key - auto-generated by the database.
     * In banking, we use auto-generated IDs because they're:
     * 1. Simple and efficient
     * 2. Not exposed externally (we use customerNumber for that)
     * 3. Guaranteed unique by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * WHY: Business key - unique across the entire banking system.
     * This is what we expose to external systems and what we
     * use to reference a customer across services.
     *
     * Example: CUST-000001, CUST-000002
     * In a real bank, this might include branch code, region, etc.
     */
    @Column(name = "customer_number", length = 20, nullable = false, unique = true)
    private String customerNumber;

    @Column(name = "first_name", length = 100, nullable = false)
    private String firstName;

    @Column(name = "last_name", length = 100, nullable = false)
    private String lastName;

    @Column(name = "email", length = 255, nullable = false)
    private String email;

    @Column(name = "phone_number", length = 20)
    private String phoneNumber;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    /**
     * WHY: Customer status controls what operations are allowed.
     * In a bank, statuses might include:
     * ACTIVE - Normal operations allowed
     * INACTIVE - Account closed, no new operations
     * BLOCKED - Suspicious activity, all operations blocked
     * PENDING_VERIFICATION - New customer, limited operations
     */
    @Column(name = "status", length = 20)
    @Builder.Default
    private String status = "ACTIVE";

    /**
     * WHY: Creation timestamp - required for auditing.
     * In banking, we track when records are created and by whom.
     * This is required by regulators like the FDIC and Basel III.
     */
    @CreationTimestamp
    @Column(name = "created_at")
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @Column(name = "created_by", length = 100)
    private String createdBy;

    @Column(name = "updated_by", length = 100)
    private String updatedBy;

    /**
     * WHY: Version field for optimistic locking.
     * In banking, we use optimistic locking to handle
     * concurrent updates. When two users try to update
     * the same customer simultaneously, the version
     * check prevents one from overwriting the other.
     */
    @Version
    @Column(name = "version")
    private Integer version;

    @OneToMany(
            mappedBy = "customer",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    @Builder.Default
    private List<Address> addresses = new ArrayList<>();
}